on: [push]

jobs:
  dotnetpack_nugetpush_job:
    runs-on:  ubuntu-latest

    env:
      projectpath: ./nugetdemo/mydotnetpacknugetpkg/mydotnetpacknugetpkg.csproj
      buildconfiguration: release
      outpath: mypkgout
      runid: ${{github.run_id}}
      githubtoken: ${{ secrets.GITHUB_TOKEN }}
      githubnugetpackageregistry: https://nuget.pkg.github.com/odnman/index.json
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setuop-dotnet@v2
        with: 
          dotnet-version: '5.0.x'
      - name: Restore with dotnet
        run:  dotnet restore ${projectpath}

      - name: Build with dotnet
        run:  dotnet build ${projectpath} --configuration ${buildconfiguration} --version-suffix ${runid} --no-restore
      
      - name: Pack as nuget with dotnet
        run:  dotnet pack ${projectpath} --configuration ${buildconfiguration} --output ${outputpath} --version-suffix ${runid} --no-build --no-restore

      - name: Publish Nuget to GitHub registry
        run:  dotnet nuget push ${outpath}/*.nupkg --api-key ${githubtoken} --source ${githubnugetpackageregistry} --skip-duplicate --no-symbols true
        